game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.ZoomFactor
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.TotalRecoilMax
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.ShowEntireTrailUntilHit
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.ShotEffect
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.RecoilMin
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.RecoilMax
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.RecoilDecay
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.NumProjectile
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.MuzzleFlashSize1
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.MuzzleFlashSize0
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.MaxDistance
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.HitMarkEffect
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.HitDamage
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.HasScope
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.ExplodeOnImpact
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.CrosshairScale
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.BlastRadius
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.BlastPressure
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.BeamWidth1
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.BeamWidth0
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.BeamFadeTime
game:GetService("Players").LocalPlayer.Backpack.Railgun.Configuration.AmmoCapacity
